name: CI/CD Pipeline

# Trigger the workflow on push to the 'main' branch or any pull request targeting 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specifies Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

  docker:
    runs-on: ubuntu-latest
    needs: build-and-test  # This job will only run if the 'build-and-test' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx, which allows building multi-platform images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Logs in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-microservice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker  # This job will only run if the 'docker' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yml  # Replace with your Kubernetes deployment file
